### ISSUE TITLE
Test failing: Add/remove multiple files and upload. Expected <input> not to exist in the DOM

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1146]
Happened here https://github.com/ChainSafe/files-ui/runs/2837287321?check_suite_focus=true

```
      AssertionError: Timed out retrying after 4000ms: Expected <input> not to exist in the DOM, but it was continuously found.
 |       at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/tests/file-management-spec.ts:194:50)
```
![image](https://user-images.githubusercontent.com/33178835/122188110-eefaef80-ce8f-11eb-9bf0-2aaa150245b1.png)

**Comment by asnaith** [comment]
I have seen this happening sporadically when running tests locally too.

It's happening when clicking the "start upload" button, sometimes cypress seems to do it too quickly after attaching the file. It seems as though the upload doesn't begin if the click is too fast and so the dialog remains in view. 

I've experimented with `should("not.be.disabled")` and `should(be.visible)` on the start upload button (before clicking it) but it didn't seem to help. 

Generic waits in between attaching the file and pressing the "start upload" button so seem to improve the situation but there must be a check we can add instead of doing that.

**Comment by asnaith** [comment]
I'm awaiting confirmation of further test runs but it seems like this is resolved by https://github.com/ChainSafe/files-ui/pull/1143/commits/4a49a4f7e03a74a3f1412dec7f2b55d5a37364d2 (or at least, I haven't seen it happen again since I added that).

**Comment by asnaith** [comment]
I spoke too soon previously...but really not seeing this issue after https://github.com/ChainSafe/files-ui/pull/1143/commits/0e7c64ee56f614f5bd2c251ac885ebb4d9e2b939 😄. 

I ran the test 100 times locally and the CI test runs have been good since too. 

@Tbaut I don't think either of us are satisfied with this need for the wait statement though. Should we keep this issue open until we have a better solution?

**Comment by Tbaut** [comment]
I found a clean way to do it: https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/
Made a PR with it, I can't see the problem any more.
