### ISSUE TITLE
Does backend api open-sourced?

### ISSUE THREAD

**Issue by badkk** [ChainSafe/files-ui#1449]
I found that when I do uploading, my file transferring through `https://api.chainsafe.io/api/v1`?  is this backend service opensourced, or just use the `powergate` by texile?

**Comment by Tbaut** [comment]
Hey Kun, thanks for your question. The backend isn't open source yet. We will most probably open source it, but there is no date as of yet. I'll close it but don't hesitate to answer to this issue if you have other questions.

**Comment by badkk** [comment]
> Hey Kun, thanks for your question. The backend isn't open source yet. We will most probably open source it, but there is no date as of yet. I'll close it but don't hesitate to answer to this issue if you have other questions.

Thanks for your reply! 
Does the backend service using `powergate` arch which will put the file into IPFS and Filecoin?
And is there any plan to support more IPFS-based decentralized chains like Arweave or Crust?

**Comment by kalambet** [comment]
Hey Kun, thank you for your interest! :)
Yes, for the FileCoin we are using `powergate` right now and we are doing batching by ourselves, plus we are looking at other options as well. We are not looking at Arweave or Crust right now but that is mostly because of the early stage of the project and we will consider all possible options and opportunities in future.

However, all the IPFS interaction are done directly with IPFS nodes and In terms of storing files on top of IPFS we are supporting two options right now: native one (used in ChainSafe Storage UI) where we are using IPFS file system (mfs) to store files hierarchy and internal one (used in ChainSafe Storage S3 compatibility layer and in ChainSafe Files) where we are storing files hierarchy information and metadata as a separate encrypted object on top of IPFS so your files disposition and file names are not visible from outside.

**Comment by badkk** [comment]
> Hey Kun, thank you for your interest! :)
> 
> Yes, for the FileCoin we are using `powergate` right now and we are doing batching by ourselves, plus we are looking at other options as well. We are not looking at Arweave or Crust right now but that is mostly because of the early stage of the project and we will consider all possible options and opportunities in future.
> 
> 
> 
> However, all the IPFS interaction are done directly with IPFS nodes and In terms of storing files on top of IPFS we are supporting two options right now: native one (used in ChainSafe Storage UI) where we are using IPFS file system (mfs) to store files hierarchy and internal one (used in ChainSafe Storage S3 compatibility layer and in ChainSafe Files) where we are storing files hierarchy information and metadata as a separate encrypted object on top of IPFS so your files disposition and file names are not visible from outside.

So glad to know that! 
And I'm the member in Crust, if you have any needs to provide more storage options, please don't hesitate to ask me. We're very happy to help you with Crust Storage service.
