### ISSUE TITLE
Downgrade Plan

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1783]
Overall flow as described in [Figma](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=5129%3A85273):

If user is over the limit of the desired plan (`is_update_allowed` is false) then offer users to remove files until they fit in to the target plan.
![image](https://user-images.githubusercontent.com/33178835/144755206-6b7fa547-4995-43ac-87aa-d070c3843831.png)

If the user is able to downgrade to the desired plan:
![image](https://user-images.githubusercontent.com/33178835/144755223-ec30adf0-0224-46c1-ab32-3188108739b3.png)

**Comment by Tbaut** [comment]
Agreed with the comments offline that the flow is overly complex, and the users could be informed about the amount of data that should be deleted and delete it themselves.

**Comment by FSM1** [comment]
> Agreed with the comments offline that the flow is overly complex, and the users could be informed about the amount of data that should be deleted and delete it themselves.

Updated with the latest designs

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1783?planning-poker) with ZenHub @tanmoyAtb @Tbaut

**Comment by Tbaut** [comment]
Updated OP with the latest design

**Comment by Tbaut** [comment]
Removing myself from this issue for now because some paths are more involved than expected and actually require more info from the api.

So let's say if a user is on a plan A($100 monthly) and wants to migrate to plan B($30 monthly) in the middle of the month. In this case he/she has $50 worth of service credit left.

So we have following cases in plan updates:
1. User downgrades/upgrade with payment method remains unchanged in case of stripe
- We support proration. Based on the above example, customer doesn't have to pay any additional money.
- We support credit. Based on the above example, $20 will be added to stripe credit which will be utilized on the next billing.
  --> we need to tell the user that their downgrade will give them $20 on any following bill.

2. User downgrades/upgrade with payment method remains unchanged in of crypto
- We support proration. Based on the example, customer doesn't have to pay any additional money.
- We don't support credit. We won't be adding $20 to credit.
  --> We need to tell the user that starting from next bill, they will need to pay the full monthly rate.

3. User downgrades/upgrade along with payment method updated
- We don't support proration. Based on the above example, customer have to pay full amount i.e. $ 30
- We don't support credit. We won't be adding $20 to credit.
  --> We need to warn the user that due to payment method change, they will need to pay the monthly rate right away.

Similarly, if a user moves from a monthly paid plan to a yearly paid plan, we'll need to get the calculation regarding what users have already paid, and what is missing.

@serenaho Could we update the Figma flow to let users select their payment method and see the error/info?

**Comment by serenaho** [comment]
@Tbaut For sure, I'll update the flow in Figma to reflect these changes!

**Comment by serenaho** [comment]
Hey @Tbaut, I have a question about the second option in the case of crypto payments you posted above.

Since we don't allow for monthly payments for crypto, if a user downgrades from plan A to plan B then we won't need to tell them to pay the full monthly rate starting from their next bill, right?

Instead, we'll say that they will need to pay again at the end of their pro-rated period. Is this correct?

**Comment by Tbaut** [comment]
Good point, tbf I'm not sure we don't allow monthly crypto payment, it's just that it doesn't make any sense for our user (for us it doesn't matter). But if someone wants to pay 10$+ in fees for something that costs 10$, I don't think we'll prevent them explicitly.

**Comment by serenaho** [comment]
Right, although since we've disabled the crypto payment option for when the user selects monthly billing, I'm assuming it probably makes sense to do this:

> Instead, we'll say that they will need to pay again at the end of their pro-rated period.

**Comment by Tbaut** [comment]
We haven't disabled the crypto payment for monthly subscription. We havent' developed the crypto payment. I really think the users should decide what's better for them. If them really really want it, why not :D

In any case the api should be designed in such a way that the UI can handle these messages in a generic way. Something like:

- Is the current payment a reduction (because of pro-rata) if yes show something like "Due to your previous credit, you only need to pay X"
- Is that credit left: we show "Your next bill will be reduced by X thanks to accumulated credits"

^ these are all very badly phrased suggestions :D

**Comment by FSM1** [comment]
> We haven't disabled the crypto payment for monthly subscription. We haven't developed the crypto payment. I really think the users should decide what's better for them. If them really really want it, why not :D
> 
There were a number of reasons to do this, but it boils down to giving us more time to refine things such as notifications for billing which will be necessary to have.
