### ISSUE TITLE
Consistent Header + Menu Font Sizing

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1907]
Small thing that I noticed while looking through the current stage is the inconsistency of text-sizing as pictured below:

![image.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/c195f094-a819-48e5-857d-f2217effb17f)

**How it should be:**

![image.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/ee519bee-ab11-4e12-8d95-ad1b5b7df099)

We don't have to strictly follow the 16px or 20px, it's just a concern of consistent/relevant sizing. The settings tab headers should also be bolded depending on which tab they're on.

**Comment by Tbaut** [comment]
I have a hard time coming up with something coherent for the settings title and sub-title. Figma can't be taken as source of truth either, since what this issue is about is actually not followed here for instance: [here](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=2999%3A61132)

My issue:

Do we have titles and sub-titles, like:
- Payment and subscriptions: title
- Plan name: sub-title

or in the Display settings
![image](https://user-images.githubusercontent.com/33178835/152803256-35fa9a21-1f8e-4bc2-be00-b7e46dfbba0a.png)
To me, 1 and 3 are actually big titles, and the rest 2 and 4 should be smaller. Also in this case 1 has an horizontal bar (we call this devider), should 3 have one too? Let me know what your thoughts are @serenaho

**Comment by serenaho** [comment]
Hey @Tbaut, I spent some time making the entire Settings more consistent and have made some changes below. About responsiveness-- I think things should look okay if we gave each page a max. width (like how we reused the Account Security page width).

**Text sizing**: 
- All menus (main nav and Settings submenu) are the same font size (i.e. 16px in Figma). 
- There are two additional header sizes excluding Settings header ( i.e. Profile and display = H2/38px and Wallet address = H3/28px). All the sizes I mentioned are just loose references and subject to however it's sized on your end.
- The text underneath each H3 is also the same size as menu items (i.e. 16px in Figma)

**Other**:
I made it so that each section has its own divider that spans the entire table. To me, it looks more put together and easier to chunk different sections. Let me know what you think!

*I also made some style changes which I'll address in a separate issue.

![Profile and display.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/4f11b786-57f4-4d78-886c-326aaa4ec5ab)

![Account security.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/96210ad2-48ff-4c35-8110-c71c253053a3)

![Subscription plan.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/db84e1a7-1080-48d0-83e3-254b90b6f2a1)
