### ISSUE TITLE
[Storage] Update app styling to align with the Files

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1968]
- [x] Add identicon based on user UUID
- [x] Scaling of nav bar at low height values
- [x] Check all modals for styling consistency
- [x] Settings tabs font sizes
- [x] Login scaling

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1968?planning-poker) with ZenHub @tanmoyAtb @Tbaut

**Comment by serenaho** [comment]
@FSM1 Here are the options we discussed :)

**Option A: Notification Menu Item / Page:**

![Page](https://user-images.githubusercontent.com/91699405/156844811-4d38dbe2-6cdd-4309-b76e-6244016923d9.png)

**Option B: Notification Popup:**
Note: For this option I opted for a Log out button instead of the user's name since it's the only option in the dropdown. IMO it looks awkward to have a dropdown at the bottom of the page. However, a third option could be the username opening to the right like in this example.

![Notification Popup](https://user-images.githubusercontent.com/91699405/156844818-a5d251bf-9fdc-4428-a017-7978489d4e80.png)
