### ISSUE TITLE
Add new ui test coverage for landing page in Files

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/files-ui#2114]
As described, add test coverage for the below scenarios:

- Navigate to the Privacy policy page
- Navigate to the Terms & Conditions page
- Navigate to ChainSafe.io from "Learn more about Chainsafe"
- Accept cookie banner on main page

**Comment by juans-chainsafe** [comment]
I will not include "Accept cookie banner on main page" testcase because "accept cookies" doesn't appear in localhost

**Comment by Tbaut** [comment]
I believe this is not a `localhost` specific issue, it's more the fact that posthog (our metric tracking system) is not properly set up in the environment and we default to not tracking anything, therefore there's no need for a banner. So if needed, we can make sure the banner actually appears. The only annoyance is that we may have to click it away for all the test run (<- not 100% sure this is needed, we should check if some tests fail because some UI element are hidden because of the banner)

**Comment by juans-chainsafe** [comment]
@Tbaut nice, if we don't close that banner in all the test cases I believe that some could fail, because is true that some elements could be hidden because of the banner, but in that case we can add to the web3Login command (at the end) to accept cookies (as well I think cypress has something to automatically accept cookies, but I'm not sure)
