### ISSUE TITLE
Wallet address missing / truncated unnecessarily on settings security tab

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2136]
**Description**
Noticed a minor issue with the display of the wallet address on the security tab

- On desktop: wallet address is truncated even though there is enough room to display it
- On mobile: wallet address is not displayed at all (see screenshots)

**Steps to Reproduce**
1. Log in 
2. Navigate to Settings > Security 
3. Adjust width of browser

**Observed behavior**
<img width="1320" alt="Screen Shot 2022-05-18 at 1 19 09 PM" src="https://user-images.githubusercontent.com/3982665/169149330-1e0b799a-e82a-4382-b7f5-df1a4217dcee.png">

<img width="492" alt="Screen Shot 2022-05-18 at 1 20 49 PM" src="https://user-images.githubusercontent.com/3982665/169149396-d139f3cb-96a5-4407-a3a6-8e5d5a2cc547.png">

**Expected behavior**
- Wallet address should be displayed in full when there's enough room horizontally to display it
- Wallet address should be displayed but truncated when there's not enough room horizontally to display it

**Desktop:**
 - OS: macOS
 Browser: Chrome (not browser specific)
 - Version: 101.0.4951.64

**Comment by Tbaut** [comment]
The fact that the address is shortened even in full view is actually the expected behavior, same for the fact that it's hidden on mobile. The reason is that the address should not matter much here, it's available in the "profile" setting and can be copied there.

We wanted to keep the screen as light as possible. The security setting is just here to tell what authentication factors you use (equally, you wouldn't have your email displayed here on mobile, unlike on desktop), and I doubt users would expect to find and copy their wallet address from there.

**Comment by asnaith** [comment]
@Tbaut Ah ok 👍. It seemed like a bug to me. I guess we can close this.
