### ISSUE TITLE
Extend change password ui test

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2156]
**Task**

Extend the current change password test to include signing out and signing back in with the new password. 

At the moment we're just assuming the change was successful if the change password elements collapse after submitting the change. 

**Additional Notes**

Whilst under test in cypress, it seems to lose the wallet address it was using after signing out. When we try to sign back in we are prompted to create a password not enter one (because it starts using a different wallet address). 

We need to work out what's happening with the address / fake metamask window that we are using, the same wallet address is should be maintained for the whole duration of the test.

**Comment by Tbaut** [comment]
This is a tricky one because the `web3login` cypress function either always uses a random new account, or it uses a fixed hard-coded one, with a fixed password. And if you start changing the password for the hardcoded account, this will conflict with other tests. If we want to fiddle with storing the state of the current test sessions, it means we'll have some stateful tests, which is not really elegant.
We are now pretty much in the realm of testing weather the `api` did its job, which is not really the idea. I think it might be better to just verify that the call to the api happened, and that we get 200 or something back.

**Comment by Tbaut** [comment]
closing for the reasons I mentioned.
