### ISSUE TITLE
[Files] Add if a file is shared and with whom

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/files-ui#2194]
**Description*
It will be nice to know if a file is shared or not, with that you can avoid sharing again a file that you already shared for example.

**Describe the solution you'd like**
I will like to have that information in, for example, File information modal, like:

- If the file is not shared just put "Not shared"
- If the file is shared, show with whom it is shared
<img width="607" alt="Screen Shot 2022-06-16 at 16 21 15" src="https://user-images.githubusercontent.com/104365141/174148590-891da023-4e36-46cf-bab8-edb49e28ea58.png">

**Describe alternatives you've considered**
Also, I don't know if is worth it, but add the information of in which shareable folder is the file 

**Additional context**

**Comment by Tbaut** [comment]
Any file in a shared folder is shared, and any file NOT in the shared folder is NOT shared. If a file ends up in a shared folder, then it's a duplicate, and we don't keep track of it.

**Comment by FSM1** [comment]
As Thibaut mentioned since this is determined on the bucket level, the indication of whom a file is shared with is determined by the bucket it is in.

![image](https://user-images.githubusercontent.com/12774278/174279976-6183be4f-b10f-4142-9ca7-1ae3b7edb0b0.png)

There is no way for us to know whether a file in the users personal bucket has been/is being shared.

**Comment by juans-chainsafe** [comment]
Make sense, thanks for the clarification guys! I will close this ticket.
