### ISSUE TITLE
Unable to sign message using EIP1193 Wallet

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#2209]
User has identified an issue that prevents authentication using Brave or other 3rd party wallet in the browser. 

Investigate why the Signature request fails to work when using the native wallet built in to Brave

**Comment by Tbaut** [comment]
Hmm I can't reproduce. I've been using the native Brave wallet (although our UI says Metamask, I actually deactivated MM) and the popup shows up, the message is signed correctly

https://user-images.githubusercontent.com/33178835/176548490-77707b49-e1db-49ff-81c9-51c1dc6ea044.mp4

**Comment by FSM1** [comment]
> Hmm I can't reproduce. I've been using the native Brave wallet (although our UI says Metamask, I actually deactivated MM) and the popup shows up, the message is signed correctly
> 
>  Brave.mp4

Hmmm interesting - The user who reported this had the `Detected Wallet` selected, and it was failing then. I am also able to successfully log in using brave wallet (with the app thinking it is metamask).

**Comment by FSM1** [comment]
Eventually once I had set up BlockWallet in Chrome, I managed to get a failure when I selected the `Detected wallet` option.
![image](https://user-images.githubusercontent.com/12774278/176691973-6136a6a0-b1a2-43c3-879a-3e46fb9d425a.png)

**Comment by Tbaut** [comment]
~ok so the problem is more a wallet detection issue from Blocknative rather than a signing issue right?~

edit: I can reproduce, checking

**Comment by Tbaut** [comment]
OK I've found out that the issue comes from the provider implementation. Our colleague Nazar explains it well here https://github.com/ChainSafe/web3.js/issues/4780

I have a solution (see linked PR), using `personal_sign` instead of sign for any unknown wallet, but I'm not certain this won't break other wallets.. so I opened an issue on the Block repo as well https://github.com/block-wallet/block-extension/issues/8
